### ISSUE TITLE
Call to a member function routeNotificationFor() on string

### ISSUE THREAD

**Issue by njoguamos** [tumainimosha/laravel-notifications-infobip#1]
Experiencing this issues when attempting to send a message

<img width="1226" alt="screenshot 2019-01-01 at 01 53 48" src="https://user-images.githubusercontent.com/29255728/50568783-2cbf3880-0d68-11e9-9956-e7534c141d63.png">

It would also be nice if you could write test (if you have time)

**Comment by tumainimosha** [comment]
Hi,

thanks for the feedback. Would definitely look into writing some tests in the near future.

For troubleshooting, could you share how you are sending the notification when getting this error. The following would be helpful

1. How you are dispatching the notification from `Controller` or other Class.
2. The Notification class dispatched
3. The Notifiable class.

I am guessing when sending the notification you are passing a `string` instead of `Notifiable` object.

Below is a sample implementation is am using in my project

### 1. How I am dispatching the notification

#### A. Using Laravel's notification facade

```php
use App\Notifications\ExampleInfobipNotification;
use Illuminate\Support\Facades\Notification;

Notification::send($user, new ExampleInfobipNotification());

// where $user implements `Illuminate\Notifications\Notifiable` trait
```

#### B. Using the `notify()` method from `Notifiable` trait

```php
use App\Notifications\ExampleInfobipNotification;

$user->notify(new ExampleInfobipNotification($invoice));
```

### 2. My notification class

```php
<?php

namespace App\Notifications;

use Illuminate\Notifications\Notification;
use NotificationChannels\Infobip\InfobipChannel;
use NotificationChannels\Infobip\InfobipMessage;

class ExampleInfobipNotification extends Notification
{
    public function via($notifiable)
    {
        return [InfobipChannel::class];
    }

    public function toInfobip($notifiable)
    {
        return (new InfobipMessage())
            // Customize your msg content here
            ->content("Your {$notifiable->service} account was approved!"); 
    }
}
```

### 3. My notifiable class

```php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
}
```


For more details you can check out [this link](https://laravel.com/docs/5.7/notifications#sending-notifications) on Laravel documentation
